package com.dartdocer.aspect

import com.intellij.psi.PsiElement
import com.jetbrains.lang.dart.psi.DartClassDefinition
import com.jetbrains.lang.dart.psi.DartComponent
import com.jetbrains.lang.dart.psi.DartEnumDefinition
import com.jetbrains.lang.dart.psi.DartExtensionDeclaration
import com.jetbrains.lang.dart.psi.DartMixinDeclaration

/* ---- shared PSI helpers ---- */

private fun DartComponent.hasAnnotation(simpleName: String): Boolean =
    metadataList.any { it.referenceExpression?.text == simpleName }

private fun DartClassDefinition.superclassName(): String? =
    superclass?.type?.referenceExpression?.text

private fun DartClassDefinition.superTypeNames(): List<String> {
    val names = mutableListOf<String>()
    superclass?.type?.referenceExpression?.text?.let { names += it }
    // DartClassDefinition extends DartClass which has getMixinsList() returning List<DartType>
    (this as? com.jetbrains.lang.dart.psi.DartClass)?.mixinsList?.forEach { dartType ->
        dartType.referenceExpression?.text?.let { names += it }
    }
    (this as? com.jetbrains.lang.dart.psi.DartClass)?.implementsList?.forEach { dartType ->
        dartType.referenceExpression?.text?.let { names += it }
    }
    return names
}

/* ---- Flutter widget aspects ---- */

/** Flutter StatelessWidget. */
object FlutterStatelessWidgetAspect : DartAspect {
    override val id = "flutter-stateless"
    override val defaultNote =
        "A [StatelessWidget] that describes part of the user interface as an immutable widget tree."

    override fun matches(element: PsiElement): Boolean =
        element is DartClassDefinition && element.superclassName() == "StatelessWidget"
}

/** Flutter StatefulWidget. */
object FlutterStatefulWidgetAspect : DartAspect {
    override val id = "flutter-stateful"
    override val defaultNote =
        "A [StatefulWidget] that can rebuild when its internal state changes."

    override fun matches(element: PsiElement): Boolean =
        element is DartClassDefinition && element.superclassName() == "StatefulWidget"
}

/** Flutter provider / state management (ChangeNotifier, StateNotifier). */
object FlutterProviderAspect : DartAspect {
    override val id = "flutter-provider"
    override val defaultNote =
        "State holder — extends [ChangeNotifier] or [StateNotifier] to notify listeners of state changes."

    override fun matches(element: PsiElement): Boolean {
        if (element !is DartClassDefinition) return false
        val supers = element.superTypeNames()
        return supers.any { it == "ChangeNotifier" || it == "StateNotifier" || it == "ValueNotifier" }
    }
}

/** Freezed / unfreezed annotated class. */
object FreezedAspect : DartAspect {
    override val id = "freezed"
    override val defaultNote =
        "Immutable data class generated by [freezed] — provides `copyWith`, pattern matching and serialization."

    override fun matches(element: PsiElement): Boolean {
        if (element !is DartClassDefinition) return false
        // DartClassDefinition extends DartComponent
        return (element as DartComponent).hasAnnotation("freezed") ||
            (element as DartComponent).hasAnnotation("unfreezed")
    }
}

/** Dart enum declaration. */
object DartEnumAspect : DartAspect {
    override val id = "enum"
    override val defaultNote = "Enum — a fixed set of named constants."

    override fun matches(element: PsiElement): Boolean = element is DartEnumDefinition
}

/** Dart mixin declaration. */
object DartMixinAspect : DartAspect {
    override val id = "mixin"
    override val defaultNote =
        "Mixin — provides reusable functionality that can be applied to classes via `with`."

    override fun matches(element: PsiElement): Boolean = element is DartMixinDeclaration
}

/** Dart extension declaration. */
object DartExtensionAspect : DartAspect {
    override val id = "extension"
    override val defaultNote =
        "Extension — adds methods and getters to an existing type without modifying it."

    override fun matches(element: PsiElement): Boolean = element is DartExtensionDeclaration
}

/** Singleton pattern (name ends with Singleton, or has factory constructor). */
object DartSingletonAspect : DartAspect {
    override val id = "singleton"
    override val defaultNote = "Singleton — a single shared instance."

    override fun matches(element: PsiElement): Boolean {
        if (element !is DartClassDefinition) return false
        val name = element.name ?: return false
        if (name.endsWith("Singleton")) return true
        // Check for factory constructor pattern with _instance field
        val classMembers = element.classBody?.classMembers ?: return false
        val hasPrivateInstance = classMembers.varDeclarationListList.any { varDecl ->
            val varName = varDecl.varAccessDeclaration?.componentName?.text
            varName == "_instance" || varName == "_${name.replaceFirstChar { c -> c.lowercase() }}"
        }
        val hasFactory = classMembers.factoryConstructorDeclarationList.isNotEmpty()
        return hasPrivateInstance && hasFactory
    }
}
